image: facio/bigbro

build:
  stage: build
  script:
    - sh build/linux.sh
  artifacts:
    paths:
      - libbigbro.a
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  # cache:
  #   paths:
  #     - "*.o"

# run tests using the binary built before
test:
  stage: test
  script:
    - cargo build --features strict
    - cargo build --features strict --release
    - python3 run-tests.py
    - echo Checking for rust warnings...
    - cargo test --features strict
    - cargo build --features strict --target i686-pc-windows-gnu
    - cargo build --features strict --target x86_64-pc-windows-gnu
  after_script:
    - bash <(curl -s https://codecov.io/bash) -t ef88c866-d33f-45e5-b994-617ef7861f50
  artifacts:
    paths:
      - web

pages:
  stage: deploy
  script:
    - git clone https://gitlab.com/facio/fac.git tests/fac
    - cd tests/fac
    - sh build/linux.sh
    - ./fac
    - cd ../..
    - tests/fac/fac
    - mv web public
  artifacts:
    paths:
      - public

