image: facio/bigbro

build:
  stage: build
  script:
    - sh build/linux.sh
  artifacts:
    paths:
      - libbigbro.a
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  # cache:
  #   paths:
  #     - "*.o"

# run tests using the binary built before
test:
  stage: test
  script:
    - python3 run-tests.py
  after_script:
    - bash <(curl -s https://codecov.io/bash) -t ef88c866-d33f-45e5-b994-617ef7861f50
  artifacts:
    paths:
      - web

pages:
  stage: deploy
  script:
    - git clone git://github.com/daveroundy/fac.git
    - cd fac
    - sh build/linux.sh
    - ./fac
    - cd ..
    - fac/fac
    - mv web public
  artifacts:
    paths:
      - public

