image: debian:stable

build:
  stage: build
  before_script:
    - apt-get update && apt-get -y install build-essential python3
  script:
    - sh build/linux.sh
  artifacts:
    paths:
      - libbigbro.a
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  # cache:
  #   paths:
  #     - "*.o"

# run tests using the binary built before
test:
  stage: test
  before_script:
    - apt-get update && apt-get -y install python3 libc6-dev-i386 gcovr
  script:
    - python3 run-tests.py
  artifacts:
    paths:
      - coverage.html
      - coverage.bigbro-linux.c.html
      - coverage.errors.h.html
      - coverage.fileaccesses.c.html
      - coverage.hashset.h.html
      - coverage.linux-proc.h.html
      - coverage.realpath.h.html

