# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

build:
  stage: build
  script:
    - sh build/linux.sh
  artifacts:
    paths:
      - libbigbro.a
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  # cache:
  #   paths:
  #     - "*.o"

# run tests using the binary built before
test:
  stage: test
  before_script:
    - apt-get update && apt-get -y install python3 libc6-dev-i386 gcovr
  script:
    - CFLAGS=--coverage python3 run-tests.py
    - gcovr -k -r . --exclude-unreachable-branches
    - gcovr -k -r . --exclude-unreachable-branches --html --html-details -o coverage.html
  artifacts:
    paths:
      - coverage.html
      - coverage.*.html
