image: facio/bigbro

build:
  stage: build
  script:
    - sh build/linux.sh
  artifacts:
    paths:
      - libbigbro.a
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  # cache:
  #   paths:
  #     - "*.o"

# run tests using the binary built before
test:
  stage: test
  script:
    - mkdir -p ~/.cargo
    - cat .cargo/config >> ~/.cargo/config
    - python3 run-tests.py
  after_script:
    - bash <(curl -s https://codecov.io/bash) -t ef88c866-d33f-45e5-b994-617ef7861f50
  artifacts:
    paths:
      - web

pages:
  stage: deploy
  script:
    - git clone https://gitlab.com/facio/fac.git tests/fac
    - cd tests/fac
    - sh build/linux.sh
    - ./fac web/style.css web/documentation.html web/doc/bigbro/index.html web/index.html
    - cd ../..
    - cargo --version
    - tests/fac/fac
    - mv web public
  artifacts:
    paths:
      - public

