image: debian:stable

build:
  stage: build
  before_script:
    - apt-get update && apt-get -y install gcc python3
  script:
    - sh build/linux.sh
  artifacts:
    paths:
      - libbigbro.a
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  # cache:
  #   paths:
  #     - "*.o"

# run tests using the binary built before
test:
  stage: test
  before_script:
    - apt-get update && apt-get -y install git gcc python3 libc6-dev-i386 gcovr curl
  script:
    - python3 run-tests.py
  after_script:
    - bash <(curl -s https://codecov.io/bash) -t ef88c866-d33f-45e5-b994-617ef7861f50
  artifacts:
    paths:
      - coverage.html
      - coverage.bigbro-linux.c.html
      - coverage.errors.h.html
      - coverage.fileaccesses.c.html
      - coverage.hashset.h.html
      - coverage.linux-proc.h.html
      - coverage.realpath.h.html

