# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
    ARCH: amd64
    VS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat

build_script:
  - cmd: SET PATH=C:\python35;%PATH%
  - if defined VS call "%VS%" amd64_x86
  - cmd: bash -c "which cl.exe"
  - cmd: python build/windows.py x86
  - if defined VS call "%VS%" amd64
  - cmd: bash -c "which cl.exe"
  - cmd: python build/windows.py amd64

# to run your custom scripts instead of automatic tests
test_script:
  - python run-windows-tests.py

branches:
  only:
    - master
