# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

os: Visual Studio 2015

platform:
  - x86
  - x64

build_script:
  - cmd: SET PATH=C:\Program Files (x86)\MSBuild\14.0\bin\;%PATH%
  - cmd: SET PATH=C:\python35;%PATH%
  - cmd: python build/windows.py

# to run your custom scripts instead of automatic tests
test_script:
  - echo This is my custom test script

branches:
  only:
    - master
