# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
    ARCH: amd64
    VS: C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat
  - TARGET: x86_64-pc-windows-msvc
    ARCH: amd64
    VS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
  - TARGET: i686-pc-windows-msvc
    ARCH: x86
    VS: C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat
  - TARGET: i686-pc-windows-msvc
    ARCH: x86
    VS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat

build_script:
  - if defined VS call "%VS%" %ARCH%
  - cmd: SET PATH=C:\python35;%PATH%
  - cmd: bash -c "which cl.exe"
  - cmd: bash -c "which link.exe"
  - cmd: python build/windows.py

# to run your custom scripts instead of automatic tests
test_script:
  - echo This is my custom test script

branches:
  only:
    - master
