# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

os: Visual Studio 2015

platform:
  - x86
  - x64

install:
  - cmd: SET PATH=C:\Program Files (x86)\MSBuild\14.0\bin\;%PATH%
  - cmd: SET PATH=C:\python35;%PATH%
  - cmd: python build/windows.py

branches:
  only:
    - master

# disable build and test pahses
build: off
test: off
