[package]
name = "bigbro"
version = "0.3.8"
authors = ["David Roundy <daveroundy@gmail.com>"]

description = "Library for tracking file accesses of processes"
license = "GPL-2.0+"
repository = "https://github.com/droundy/bigbro"
homepage = "https://facio.gitlab.io/bigbro"
documentation = "http://facio.gitlab.io/bigbro/doc/bigbro/index.html"

build = "build.rs"

[badges]
gitlab = { repository = "facio/bigbro", branch = "master" }

[lib]
name = "bigbro"
path = "src/lib.rs"

[[bin]]
name = "test-bigbro"
path = "src/bin.rs"

[[bin]]
name = "test-bigbro-twostep"
path = "src/twostep.rs"

[[bin]]
name = "test-bigbro-chan"
path = "src/test-chan.rs"

[dependencies]

libc = "^0.2"

[build-dependencies]
gcc = "0.3"

[features]
# Treat warnings as a build error.
strict = []
