[package]
name = "bigbro"
version = "0.1.0"
authors = ["daveroundy@gmail.com"]
build = "build.rs"

[lib]
name = "bigbro"
path = "src/lib.rs"

[[bin]]
name = "test-bigbro"
path = "src/bin.rs"

[dependencies]

libc = "^0.2"

[build-dependencies]
gcc = "0.3"

[features]
# Treat warnings as a build error.
strict = []
